### ISSUE TITLE
Integrate ThemeProvider

### ISSUE THREAD

**Issue by kof** [cssinjs/styled-jss#20]
@iamstarkov has been working on a unified styling solution https://github.com/iamstarkov/theming and styled-jss needs to integrate it

Main issue https://github.com/cssinjs/jss/issues/488

**Comment by iamstarkov** [comment]
I need feedback, pls take a look https://github.com/iamstarkov/theming/pull/2

**Comment by iamstarkov** [comment]
@lttb, react-jss got a theming support in latest release. lemme know if you need any help to fix this issue

**Comment by kserjey** [comment]
How it goes?

**Comment by lttb** [comment]
hi @kserjey, it's already almost done, planning to integrate it this week https://github.com/cssinjs/styled-jss/pull/35 (just need to upgrade `theming` version with React 16 support)

**Comment by ndelangen** [comment]
This would certainly help, this is a pretty important step to get this package more usable in my humble opinion. 

Thanks, awesome work!

**Comment by Pentiado** [comment]
Is there a way to use a theme with Base Stylesheet (https://github.com/cssinjs/styled-jss/blob/master/README.md#base-style-sheet) or it isn't supported yet? I would expect something like this to work

`````
Styled((theme) => ({
  header: {
    margin: 10,
    color: theme.colorHeader,
  },
}));
`````
