### ISSUE TITLE
Compose React Components with styled-jss

### ISSUE THREAD

**Issue by thupi** [cssinjs/styled-jss#39]
Why do this not work :-) ? I am used to do so in other styled component libs :-) ?

https://www.webpackbin.com/bins/-Kqj9we_BMAsxT1ISrUc

**Comment by kof** [comment]
Sounds like a valid use case, didn't know it doesn't

**Comment by thupi** [comment]
Sounds great :-) 

I haven't yet looked into the implementation of styled-jss but could this be solved by passing classNames to the component if the first parameret is a React component :-) ?

**Comment by lttb** [comment]
hi, @thupi!

Thanks for this issue!

Composition works only with *styled* components now, but I think it's reasonable to implement such a behavior. I'll try to fix this as soon as possible

**Comment by thupi** [comment]
Hi @lttb.

Sounds realy great :-) ! There is many styled component libaries at the moment but material-ui works great with jss :-) ! I realy look forward to such a implementaion :-)

**Comment by lttb** [comment]
@thupi sorry for the such delay, but we've finally released this feature :)

You can check it here: https://www.webpackbin.com/bins/-KwJ9qyb46vhSTKBaqDh
