### ISSUE TITLE
React 16 compatibility

### ISSUE THREAD

**Issue by hburrows** [cssinjs/styled-jss#42]
This package is dependent on `is-react-prop` which isn't (currently) compatible with React 16.  Do you have plans to remediate this?  Is there a timeframe for this?

**Comment by lttb** [comment]
Hello!

Sure! Unfortunately, I had no time to fix this issue earlier, but I've got plans to release the next version of `is-react-prop` that will be compatible with React 16 and to update `styled-jss` this weekend.

**Comment by hburrows** [comment]
Any update on this?  I'm starting to wonder if this project is maintained and if I should switch to `styled-components`.  It's listed as on "official" integration for JSS but doesn't seem to be getting any attention.  Given that React 16 has been in the works for a long time and nothing has been updated in this repo for 3+ months I'm wondering about its status -- can't be that "official".

**Comment by kof** [comment]
Hi @hburrows, I understand that you are worried, but please resist from exercising pressure. 

We are working on it mostly in our spare time for free and so sometimes real life comes first!!!!!

@lttb has planned a bunch of updates, which he is going to execute as soon as possible.

**Comment by lttb** [comment]
hi @hburrows,

I'm working on the release of `styled-jss` with react 16 support, there are also some updates with new features, core updates and so on, and I just want to make sure, that it's production-ready.

Unfortunately, I haven't finished this work on the weekend, but I'm trying to release it as soon as possible.

I'm going to release react 16 support in the coming days as alfa release, so it will be a pleasure to me if you will have a chance to check it.

**Comment by hburrows** [comment]
@kof @lttb Sorry about the tone of my message.  I'm not trying to be a jerk and unsympathetic - I totally understand how OOS works and really appreciate the work you guys are doing and the sacrifice it involves.  I've been in dependency hell the last couple of days and this project has been a big source of friction.  Thank-you for your quick responses - it reassures me you're committed to maintaining this.   @lttb happy to alpha & beta test when it's ready.

**Comment by lttb** [comment]
@hburrows I'm glad to inform you that we've just release beta version of `styled-jss` (currently 2.0.0-beta.3) with support of React 16 https://github.com/cssinjs/styled-jss/pull/43

You can check an example [here](https://www.webpackbin.com/bins/-KvdBKFTmNelR8qFQGEo)

It may take some time to make sure that everything is ok and to prepare for the major release, but I hope that it will be ready for the stable version this week.

**Comment by hburrows** [comment]
Sweet!!!  I will take it for a test drive shortly.

**Comment by hburrows** [comment]
I got blocked by `theming` which `react-jss` is dependent on which also doesn't yet support React 16.  As soon as this is resolved I can proceed with testing this.  I'm using both `react-jss` and `styled-jss` together.  `material-ui@v1-beta` is dependent on `react-jss@7.2.0` so not sure how they're dealing with it (or if they are) ??

**Comment by lttb** [comment]
Closed by https://github.com/cssinjs/styled-jss/pull/43
