### ISSUE TITLE
Add plugins without re-exporting styled

### ISSUE THREAD

**Issue by goodmind** [cssinjs/styled-jss#56]
Is this possible to add jss plugins without re-exporting whole `styled-jss` module?

**Comment by lttb** [comment]
hm, in the beginning, we thought that it would be better to provide `jss` customization by `createStyled` function as in the example in the readme.

but maybe it would be okay to provide jss instance with `styled` function like `styled.jss`, so with that you will have an ability to add plugins this way: `styled.jss.use(vendorPrefixer())`

what do you think?

**Comment by goodmind** [comment]
@lttb looks ok

**Comment by lttb** [comment]
@goodmind released in 2.1.1, hope it helps

**Comment by goodmind** [comment]
@lttb is this supposed to work like this? Nested selector didn't added to stylesheet
https://www.webpackbin.com/bins/-Ky6Kf7GAuosMZ5Jm1z4

**Comment by lttb** [comment]
@goodmind it looks like that `jss-isolate` does not apply for cascaded selectors (https://www.webpackbin.com/bins/-Ky6UVkomYxYn8mUF4cu)

**Comment by lttb** [comment]
opened an issue: https://github.com/cssinjs/jss/issues/619
