### ISSUE TITLE
Code Style: express acronyms in capital space

### ISSUE THREAD

**Issue by DenisIzmaylov** [cssinjs/styled-jss#8]
**Basic requirements:**

+ Keep source code as documentation - lexically and grammarly correct. 
+ Keep signatures and API compliant with general (native) API.
+ Express acronyms in capital spaces, e.g. [encodeURIComponent](https://developer.mozilla.org/nl/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), [SIMD](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD), [decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI),
 [JSON](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON), [NaN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN), [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError), [cipher:setAAD](https://nodejs.org/dist/latest-v7.x/docs/api/crypto.html#crypto_cipher_setaad_buffer) and so on.
+ Keep API predictable - you just know if some part in a name is acronym then write it in capital case. You should not remember where is to write acronyms in lower case, etc. That's why we've updated [this pull request](https://github.com/axept/prejss-postcss-parser/pull/1).

**Current state:**

+ README:

   ```
   const jss = createJss()
   ```

+ Probably other places (did not explored the source code deeply yet).

**Comment by lttb** [comment]
Thanks for watching!
And there is also rule about capitalized acronyms here https://github.com/airbnb/javascript#naming--Acronyms-and-Initialisms

So we have discussed a little with @kof (https://github.com/cssinjs/styled-jss/pull/1#discussion_r112584469, https://github.com/cssinjs/styled-jss/pull/1#discussion_r112573844) about this style too, and I see this way:
- use strict camelCase for everything except CONSTANTS
- use lowercase for instances, PascalCase for classes/constructors (like https://github.com/airbnb/javascript#naming--PascalCase)

**Comment by DenisIzmaylov** [comment]
This rule (  https://github.com/airbnb/javascript#naming--Acronyms-and-Initialisms ):

> Acronyms and initialisms should always be all capitalized, or all lowercased.

Provides a two variants. More variants - more complexity and errors. I'd just like to see less complexity and less errors in our projects.

**Comment by iamstarkov** [comment]
I don't understand the issue

**Comment by kof** [comment]
Javascript is not consistent with that as well: for e.g. XMLHttpRequest - even in one word 2 different conventions.

Using strict version is easier, we don't need to think how to name it. Less rules apply. Its also a very popular convention, I would rather stick with this.

**Comment by iamstarkov** [comment]
me too

**Comment by kof** [comment]
Also with strictCamelCase its possible to convert from snake_case automatically.

**Comment by iamstarkov** [comment]
lets not change anything for now and re-iterate in a few months
